/* eslint-disable no-undef */

define([], function() {
  return {
    // "userLang": "EN",
    "PropertyPaneDescription": "Description",
    "BasicGroupName": "Group Name",
    "DescriptionFieldLabel": "Description Field",
    "AppLocalEnvironmentSharePoint": "The app is running on your local environment as SharePoint web part",
    "AppLocalEnvironmentTeams": "The app is running on your local environment as Microsoft Teams app",
    "AppLocalEnvironmentOffice": "The app is running on your local environment in office.com",
    "AppLocalEnvironmentOutlook": "The app is running on your local environment in Outlook",
    "AppSharePointEnvironment": "The app is running on SharePoint page",
    "AppTeamsTabEnvironment": "The app is running in Microsoft Teams",
    "AppOfficeEnvironment": "The app is running in office.com",
    "AppOutlookEnvironment": "The app is running in Outlook",
    "title_details": "Details",
    "provide_bilingual_name": "Provide <strong className={ styles.blue }>bilingual</strong>\nnames and descriptions",
    "create_a_community": "Create a community",
    "community_details": "Community details",
    "community_classification": "Community classification",
    "community_classification_Modal": "<span style=fontWeight:normal>a</span> Community classification",
    // "terms":"Protected community terms of use",
    "invite_owners_title": "Invite owners",
    "review_submit":"Review and submit",
    // "unclassified_button": "I don't want to store protected documents anymore",
    "CommPurpose": 'The GCX Support Team needs to know the purpose of the new community to determine whether it can be <strong>approved</strong>.<br/> This will not show up on your site. Write it in the official language of your choice. Max. 500 characters.',
    "title_complete": "Complete!",
    "thank_you": "Thank you for your submission.",
    "complete_content":"You will receive an email when your community has been created with everything you need to get started! (Within 48 hours Monday to Friday).",
    "complete_content2": "If you do not receive the email or have any questions, please submit a service request using the <a href=https://gcxgce.sharepoint.com/sites/Support  target={_blank} rel={noopener}>GCXchange Support portal</a>",
    "complete_img_alt":"Three people celebrating",
    "complete_button": "GCXchange Homepage",
    "commPurpose_title": "Community purpose",
    "commPurpose_Modal": "<span style=fontWeight:normal>the</span><strong> Community purpose</strong>",
    "commPurpose_desc": 'The GCX Support Team needs to know the purpose of the new community to determine whether it can be <strong>approved</strong>.',
    "commPurpose_Instruction":"This will not show up on your site. Write it in the official language of your choice. Must be between 5 and 500 characters in length.",
    "engName_title": 'English community name',
    "engName_Modal": '<span style=fontWeight:normal>the</span><strong> English community name</strong>',
    "engName_desc": 'The community’s name is the title of your community. Create a short descriptive name. A bilingual name complies with the Official Languages Act and makes it easier for others to find your community in the GCXchange Catalogue.',
    "engName_Instruction": "Use keywords, not abbreviations, to help people find your community. Must be between 5 and 80 characters in length. Only alphabets (with French accents), numbers, spaces and apostrophes are allowed.",
    "frCommName_title": "French community name",
    "frCommName_Modal": "<span style=fontWeight:normal>the</span><strong> French community name</strong>",
    "frCommName_desc":"The community’s name is the title of your community. Create a short descriptive name. A bilingual name complies with the Official Languages Act and makes it easier for others to find your community in the GCXchange Catalogue. ",
    "frCommName_Instruction": "Use keywords, not abbreviations, to help people find your community. Must be between 5 and 80 characters in length. Only alphabets (with French accents), numbers, spaces and apostrophes are allowed.",
    "shEngDesc_title": 'Short English description',
    "shEngDesc_Modal": "<span style=fontWeight:normal>the</span><strong> Short English description</strong>",
    "shEngDesc_desc": 'The community description will be visible to users when they use the “All Communities” page and when they search for it. ',
    "shEngDesc_Instruction": 'Must be between 5 and 100 characters.',
    "shFrDesc_title": 'Short French description',
    "shFrDesc_Modal": 'Short French description',
    "shFrDesc_desc": 'The community description will be visible to users when they use the “All Communities” page and when they search for it. ',
    "shFrDesc_Instruction": 'Must be between 5 and 100 characters.',
    "owners_Instruction": ' Start typing an owner’s email address to find and add them.',
    "owners_instruction_Callout": "Start typing an owner’s email address (who is registered to GCXchange) to find and add them.",

    "collaborate":"Collaborate with colleagues across departments using Microsoft Teams\n and SharePoint to share ideas, documents, and much more. Make sure to only store <strong>unclassified documents</strong>",
    "a_few_things":"A few things before you start",
    "to_create": "To create a community, you will need to:",
    "bilingual_name_smallText": "Community name and description need to be fully bilingual to comply with the <i>Official Languages Act</i>",
    "indentify_one_more_owner": "Identify at least <strong className={ styles.blue }>one more owner</strong>\n already registered to GCXchange",
    "indentify_one_more_owner_smallText": "Identifying more than one owner ensures the continuity of the community if one owner leaves",
  
    "Lets_go": "Let's go",
    "comm_desc_title": "Community description",
    "comm_name":"Community name",
   
    "unclassified": "The information you are storing is unclassified so you won't need a classified document space. Make sure <strong>not to store</strong> any classified documents in your library. If you are unsure what information is classified you can check with your departmental security policy or information management branch.",
    
    "invite_owners_para1": "As a GCXchange owner you can modify your community and invite other users to your site so they can collaborate with you in Microsoft Teams.",
    "invite_owners_para2": "We need you to <strong>add at least one more owner other than yourself</strong> before your community can be created.",
   
    "invite_owners_label":"Invite owners already registered to GCXchange.",


    "review_info":"Review the information below and make any required changes before submitting.",
    "prev_btn":"Previous",
    "next_btn": "Next",
    "submit_btn": "Let’s do this",
    'eng_desc': 'English description',
    'fr_desc': 'French description',
    'owners':'Owners',
 
    'close': 'Close',
    'you_must':'You must',
    'provide': '<span style="fontWeight:normal"> provide </span>',
    'agree':'<span style="fontWeight:normal"> agree to all </span>',
  
    'before_proceeding': 'before proceeding.',
    'and': '<span style="fontWeight:normal"> and </span>',
    'the': '',
    'classification': 'Classification',
    'term_of_use': 'Terms of use',
 
    'one_more_owner':'<strong> add at least one more</strong> owner',
    
    'select': '<span style="fontWeight:normal"> select </span>',
    'failed_oops': 'Oops, something went wrong!',
    'failed_txt1': 'Let us try to make it right.',
    'failed_txt2': 'The GCXchange Support team will create the community on your behalf. Once created, you will receive an email with everything you need to get started!',
    'failed_txt3': 'Our team will respond within 24 to 48 hours Monday to Friday.',
    'failed_txt4': 'If you do not receive the email or you do have any questions, please submit a service request using the',
    "submissionFailed": "Submission failed",
    'submitting_your_information': 'Grab a sip of coffee, we are submitting your information.',

    'max500_validation': 'Must be between 5 and 500 characters in length.',
    'special_char_validation': 'Special characters are not permitted.',
    'between_5_80_char_validation': 'Must be between 5 and 80 characters in length.',
    'max100_validation':'Must be between 5 and 100 characters.',

    'infoIcon_CommPurpose':'Information about Community purpose',
    'infoIcon_engName':'Information about English community name',
    'infoIcon_frName':'Information about French community name',
    'infoIcon_engDesc':'Information about English community description',
    'infoIcon_frDesc':'Information about French community description',
    'infoIcon_Owners':'Information about owners',

    'required': 'required field',
    "SP_TeamsLogos": "SharePoint and Teams logos with arrows indicating the sharing capability between the tools.",
    "valid_email": "<span style= fontWeight:normal>You must add a valid email.</span>",
    "invalidEmail":"<span style= fontWeight:normal>add a valid email;</span>",
    "is_not_valid": "<span style= fontWeight:normal>is not valid. Please add a valid email</span>",
    "requestorUser":"As the requester of this community, you are automatically added as an owner. You <strong>cannot invite yourself as an owner.</strong> Please remove yourself",
    "onlyAlphabets": "Only alphabets (with French accents), numbers, spaces and apostrophes are allowed.",
    "oops": "Oops!",
    "minCharacters":"Must be at least 5 characters in length.",
    "remove_special_char": "Please remove the following special characters:",
    "blankField":"Cannot be left blank.",
    "please_add_a_longer_purpose":"Please add a longer purpose.",
    "please_add_a_longer_name" : "Please add a longer name.",
    "please_add_a_longer_description": "Please add a longer description.",
    "please_add_a_purpose":"Please add a purpose.",
    "please_add_a_name" : "Please add a name.",
    "please_add_a_description": "Please add a description.",
    "invite_yourself":"Cannot invite yourself.",
    "please_remove_your_name":"Plese remove your name.",
 
    "please_add_another_owner":"Please add another owner",
    "isInvalidEmail": "Please remove the following invalid email:",
    "please_review_the_following_fields": "Please review the following fields",
    "owners_other_than_yourself": "Owners (other than yourself)",
    "owner_cannot_be_blank": "Cannot be left blank. Please add another owner.",
    "owner_cannot_invite_yourself":"Cannot invite yourself. Please remove your name.",
    "owners": "Owners",

    



  
  }
})