/* eslint-disable no-undef */
define([], function() {
  return {
    // "userLang": "EN",
    "PropertyPaneDescription": "Description",
    "BasicGroupName": "Group Name",
    "DescriptionFieldLabel": "Description Field",
    "AppLocalEnvironmentSharePoint": "The app is running on your local environment as SharePoint web part",
    "AppLocalEnvironmentTeams": "The app is running on your local environment as Microsoft Teams app",
    "AppLocalEnvironmentOffice": "The app is running on your local environment in office.com",
    "AppLocalEnvironmentOutlook": "The app is running on your local environment in Outlook",
    "AppSharePointEnvironment": "The app is running on SharePoint page",
    "AppTeamsTabEnvironment": "The app is running in Microsoft Teams",
    "AppOfficeEnvironment": "The app is running in office.com",
    "AppOutlookEnvironment": "The app is running in Outlook",
    "title_details": "Details",
    "provide_bilingual_name": "Provide <strong className={ styles.blue }>bilingual</strong>\nnames and descriptions",
    "create_a_community": "Create a community",
    "community_details": "Community details",
    "community_classification": "Community classification",
    "community_classification_Modal": "<span style=fontWeight:normal>a</span> Community classification",
    // "terms":"Protected community terms of use",
    "invite_owners_title": "Invite owners",
    "review_submit":"Review and submit",
    // "unclassified_button": "I don't want to store protected documents anymore",
    "CommPurpose": 'The GCX Support Team needs to know the purpose of the new community to determine whether it can be <strong>approved</strong>.<br/> This will not show up on your site. Write it in the official language of your choice. Max. 500 characters.',
    "title_complete": "Complete!",
    "thank_you": "Thank you for your submission.",
    "complete_content":"You will receive an email when your community has been created with everything you need to get started! (Within 48 hours Monday to Friday).",
    "complete_content2": "If you do not receive the email or have any questions, please submit a service request using the <a href=https://devgcx.sharepoint.com/sites/Support  target={_blank} rel={noopener}>GCXchange Support portal</a>",
    "complete_img_alt":"Three people celebrating",
    "complete_button": "GCXchange Homepage",
    "commPurpose_title": "Community purpose",
    "commPurpose_Modal": "<span style=fontWeight:normal>the</span> Community purpose",
    "commPurpose_desc": 'The GCX Support Team needs to know the purpose of the new community to determine whether it can be <strong>approved</strong>.',
    "commPurpose_Instruction":"This will not show up on your site. Write it in the official language of your choice. Must be between 5 and 500 characters in length.",
    "engName_title": 'English community name',
    "engName_Modal": '<span style=fontWeight:normal>the</span> English community name',
    "engName_desc": 'The community’s name is the title of your community. Create a short descriptive name. A bilingual name complies with the Official Languages Act and makes it easier for others to find your community in the GCXchange Catalogue.',
    "engName_Instruction": "Use keywords, not abbreviations, to help people find your community. Must be between 5 and 80 characters in length. Only alphabets (with French accents), numbers, spaces and apostrophes are allowed.",
    "frCommName_title": "French community name",
    "frCommName_Modal": "<span style=fontWeight:normal>the</span> French community name",
    "frCommName_desc":"The community’s name is the title of your community. Create a short descriptive name. A bilingual name complies with the Official Languages Act and makes it easier for others to find your community in the GCXchange Catalogue. ",
    "frCommName_Instruction": "Use keywords, not abbreviations, to help people find your community. Must be between 5 and 80 characters in length. Only alphabets (with French accents), numbers, spaces and apostrophes are allowed.",
    "shEngDesc_title": 'Short English description',
    "shEngDesc_Modal": "<span style=fontWeight:normal>the</span> Short English description",
    "shEngDesc_desc": 'The community description will be visible to users when they use the “All Communities” page and when they search for it. ',
    "shEngDesc_Instruction": 'Must be between 5 and 100 characters.',
    "shFrDesc_title": 'Short French description ',
    "shFrDesc_Modal": '<span style=fontWeight:normal>the</span> Short French description ',
    "shFrDesc_desc": 'The community description will be visible to users when they use the “All Communities” page and when they search for it. ',
    "shFrDesc_Instruction": 'Must be between 5 and 100 characters.',
    "owners_Instruction": ' Start typing an owner’s email address to find and add them.',
    "owners_instruction_Callout": "Start typing an owner’s email address (who is registered to GCXchange) to find and add them.",
    // "members_Instruction": 'Start typing an owner’s last name to find and add them.',
    // "community_classification_desc": "To change the classification of your community, you need to go back to the Community classification page, and read the terms of use.",
    // "community_classification_link": "<u> Go to the <i>Community classification</i> page</u> ",
    "collaborate":"Collaborate with colleagues across departments using Microsoft Teams\n and SharePoint to share ideas, documents, and much more. Make sure to only store <strong>unclassified documents</strong>",
    "a_few_things":"A few things before you start",
    "to_create": "To create a community, you will need to:",
    "bilingual_name_smallText": "Community name and description need to be fully bilingual to comply with the <i>Official Languages Act</i>",
    "indentify_one_more_owner": "Identify at least <strong className={ styles.blue }>one more owner</strong>\n already registered to GCXchange",
    "indentify_one_more_owner_smallText": "Identifying more than one owner ensures the continuity of the community if one owner leaves",
    // "protected_or_unclassified": "Invite colleagues to <strong className={ styles.blue }>register to GCXchange</strong> prior to adding them to a community",
    // "protected_or_unclassified_smallText": "Colleagues not yet registered for GCXchange can <a href=https://devgcx.sharepoint.com >register to GCXchange</a>",
    "Lets_go": "Let's go",
    "comm_desc_title": "Community description",
    "comm_name":"Community name",
    // "unclassified_cardText": "No, I don’t need to store protected information. <strong>All users will be able to find your community, and search for it</strong>.",
    // "protected_cardText":"Yes, I need to store protected information such as: consent forms, personal information, contact details for individuals or organizations, financial documentation, or other documents that, if compromised, <strong>could cause injury to an individual, organization or the government</strong>.",
    // "comm_classification_para1":"You may need to store protected documents or information in your community’s library. GCXchange can provide a space for protected information up to Protected B. First, let’s find out whether you will be storing protected documents in your community.",
    "unclassified": "The information you are storing is unclassified so you won't need a classified document space. Make sure <strong>not to store</strong> any classified documents in your library. If you are unsure what information is classified you can check with your departmental security policy or information management branch.",
    // "protected_para1":"Looks like you need a space to store protected documents and information on GCXchange. We have a few terms of use for protected communities.",
    // "protected_para2":"The security of documents is the responsibility of all members on GCXchange, including yourself. We ask that you review your departmental security guidelines to make sure you are familiar with your responsibilities and so that you can inform your members about their responsibilities, before agreeing to the terms of use below.",
    // "agree_to_terms":"I agree to the terms of use below",
    // "chk1":"Protected communities are only visible to members that have been invited by the community's owner.",
    // "chk1b":"I understand that my community will only be visible to members.",
    // "chk2":"All members of a protected community must have a government-issued phone with the Microsoft Authenticator app enabled.",
    // "chk2b":"I understand that my community members must meet these requirements to access my community.",
    // "chk3":"All members must use a government-issued device and have MyKey activated to access a protected B community.",
    // "chk3b":"I understand that my community members must meet these requirements to access my community.",
    // "chk4":"Users must have reliability clearance to access a protected space, and a need to know the information stored within.",
    // "chk4b":"I understand that my community members must meet these requirements to access my community.",
    // "chk5":"We can't guarantee timely support for classified communities. Our Support Team doesn't have direct access to these sites until they are added as members.",
    // "chk5b":"I agree to limited access to GCXchange support.",
    // "chk6":"Only users with a need to know protected information should be included in a community. When a member changes roles this need to know changes too.",
    // "chk6b":"I will regularly review membership on my community and remove members who have changed roles.",
    // "chk7":"GCXchange has a retention policy of 2 years for all documents and should only be used to store transitory information.",
    // "chk7b":"I agree to back up my community documents on my department's official repository if they contain information of business value.",
    "invite_owners_para1": "As a GCXchange owner you can modify your community and invite other users to your site so they can collaborate with you in Microsoft Teams.",
    "invite_owners_para2": "We need you to <strong>add at least one more owner other than yourself</strong> before your community can be created.",
    // "invite_owners_para3": "If you don’t want to invite members just yet, no problem. We will provide detailed instructions on how to do this once your community has been created.",
    "invite_owners_label":"Invite owners already registered to GCXchange.",
    // "invite_members":"Invite members",
    // "invite_user_not_found": "<strong>Can't find someone?</strong> It's likely they haven't registered yet for GCXchange. You can invite them to join GCXchange using the button below. Once they are registered, you will be able to add them to your community.",
    // "invite_a_colleague": "Invite a colleague to GCXchange",
    "review_info":"Review the information below and make any required changes before submitting.",
    "prev_btn":"Previous",
    "next_btn": "Next",
    "submit_btn": "Let’s do this",
    'eng_desc': 'English description',
    'fr_desc': 'French description',
    'owners':'Owners',
    // 'members':'Members',
    'close': 'Close',
    'you_must':'You must',
    'provide': '<span style="fontWeight:normal"> provide </span>',
    'agree':'<span style="fontWeight:normal"> agree to all </span>',
    'forget':'Did you forget something?',
    'before_proceeding': 'before proceeding.',
    'and': '<span style="fontWeight:normal"> and </span>',
    'the': '',
    'classification': 'Classification',
    'term_of_use': 'Terms of use',
    // 'owners_and_members': 'Owners',
    // 'unclassified_cardTitle': 'Unclassified community',
    // 'protected_cardTitle': 'Protected A or B community',
    'one_more_owner':'<strong> add at least one more</strong> owner',
    // 'second_owner': '<span style="fontWeight:normal"> one more</span> owner',
    'select': '<span style="fontWeight:normal"> select </span>',
    'failed_oops': 'Oops, something went wrong!',
    'failed_txt1': 'Let us try to make it right.',
    'failed_txt2': 'The GCX Support team will create the community on your behalf. Once created, you will receive and email with everything in you need to get started!',
    'failed_txt3': 'Our team will respond within 24 to 48 hours Monday to Friday.',
    'failed_txt4': 'If you do not receive the email or you do have any questions, please submit a service request using the',
    "submissionFailed": "Submission failed",
    'submitting_your_information': 'Grab a sip of coffee, we are submitting your information.',    
    'max500_validation': 'Must be between 5 and 500 characters in length.',
    'special_char_validation': 'Special characters are not permitted.',
    'between_5_80_char_validation': 'Must be between 5 and 80 characters in length.',
    'max100_validation':'Must be between 5 and 100 characters.',
    'infoIcon_CommPurpose':'Information about Community purpose',
    'infoIcon_engName':'Information about English community name',
    'infoIcon_frName':'Information about French community name',
    'infoIcon_engDesc':'Information about English community description',
    'infoIcon_frDesc':'Information about French community description',
    'infoIcon_Owners':'Information about owners',

    'required': 'required field',
    "SP_TeamsLogos": "SharePoint and Teams logos with arrows indicating the sharing capability between the tools.",
    "valid_email": "a valid email.",
    "is_not_valid": "is not valid.",
    "owners_modal":"<span style= fontWeight:normal >As the requester of this community, you are automatically added as an owner. You </span>cannot invite yourself as an owner</strong>.<span style= fontWeight:normal > Please remove yourself before proceeding.</span>",



  
  }
})