/* eslint-disable no-undef */
define([], function() {
  return {
      "secondcontent": "Deuxième contenu",
      "PropertyPaneDescription": "Description",
      "BasicGroupName": "Nom de groupe",
      "title_details": "Détails",
      "provide_bilingual_name": "Fournir un nom et des descriptions <strong>bilingues.",
      "create_a_community": "Créer une collectivité",
      "community_details": "Détails de la collectivité",
      "community_classification": "Classification de la collectivité",
      "terms": "Conditions d’utilisation des collectivités protégées",
      "invite_owners_members": "Inviter les responsables et les membres",
      "review_submit":"Vérifier et soumettre",
      "unclassified_button": "Je ne veux plus stocker de documents protégés.",
      "commPurpose_title": "Objet de la collectivité",
      "commPurpose_desc": 'L’équipe de soutien GCÉ doit connaître l’objectif de la nouvelle collectivité pour déterminer si elle peut être <strong>approuvée</strong>.',
      "commPurpose_Instruction": "Cette information n’apparaîtra pas sur votre site. Rédiger l’information dans la langue officielle de votre choix. Max. 500 caractères.",
      "engName_title": 'Nom de la collectivité en anglais',
      "engName_desc": "Le nom de la collectivité est le titre de votre collectivité. Créer un nom court et descriptif. Un nom bilingue respecte la Loi sur les langues officielles et permet aux autres de trouver plus facilement votre collectivité dans le catalogue GCÉchange. ",
      "engName_Instruction": "Utiliser des mots-clés, et non des abréviations, pour une meilleure visibilité. La longueur doit être de 5 à 125 caractères et les caractères spéciaux ne sont pas autorisés",
      "frCommName_title": "Nom de la collectivité en français",
      "frCommName_desc":"Le nom de la collectivité est le titre de votre collectivité. Créer un nom court et descriptif. Un nom bilingue respecte la Loi sur les langues officielles et permet aux autres de trouver plus facilement votre collectivité dans le catalogue GCÉchange. ",
      "frCommName_Instruction": 'Utiliser des mots-clés, et non des abréviations, pour une meilleure visibilité. La longueur doit être de 5 à 125 caractères et les caractères spéciaux ne sont pas autorisés.',
      "shEngDesc_title": 'Brève description en anglais',
      "shEngDesc_desc": 'La description de la collectivité sera visible pour les utilisateurs lorsqu’ils utiliseront la page « Toutes les collectivités » et lorsqu’ils font une recherche.',
      "shEngDesc_Instruction": 'Max. 33 caractères.',
      "shFrDesc_title": 'Brève description en français ',
      "shFrDesc_desc": 'La description de la collectivité sera visible pour les utilisateurs lorsqu’ils utiliseront la page « Toutes les collectivités » et lorsqu’ils font une recherche.',
      "shFrDesc_Instruction": 'Max. 33 caractères.',
      "owners_Instruction": 'Commencez à taper le nom de famille d’un membre pour le trouver et l’ajouter.',
      "members_Instruction": 'Commencez à taper le nom de famille d’un membre pour le trouver et l’ajouter.',
      "community_classification_desc": "Pour modifier la classification de votre collectivité, vous devez retourner à la page sur la classification de la collectivité et lire les conditions d’utilisation.",
      "community_classification_link": "Accéder à la page Classification de la collectivité",
      "collaborate": "Collaborer avec des collègues d’autres ministères en utilisant Microsoft Teams et Sharepoint pour échanger des idées, des documents, et bien plus encore…",
      "a_few_things":"Quelques directives avant de commencer",
      "to_create": "Pour créer une collectivité, vous devrez :",
      "bilingual_name_smallText":"Indiquer le nom et la description de la collectivité et le tout doit être entièrement bilingue pour respecter la <i>Loi sur les langues officielles</i>",
      "indentify_one_more_owner": "Indiquer au moins <strong className={ styles.blue }>un autre responsable</strong>",
      "indentify_one_more_owner_smallText": "La désignation de plus d’un responsable garantit la continuité de la collectivité en cas de départ d’un responsable",
      "protected_or_unclassified": "Indiquer si votre collectivité présentera des renseignements de niveau <strong className={ styles.blue }>Protégé</strong> ou <strong className={ styles.blue }>Non classifié</strong>",
      "protected_or_unclassified_smallText": "Les conditions de création d’une collectivité protégée devront être acceptées avant la création d’une collectivité",
      "Lets_go": "C’est parti…",
      "comm_desc_title": "Description de la collectivité",
      "comm_name":"Nom de la collectivité",

   

  }
});