/* eslint-disable no-undef */
define([], function() {
    return {
        "secondcontent": "Deuxième contenu",
        "PropertyPaneDescription": "Description",
        "BasicGroupName": "Nom de groupe",
        "title_details": "Détails",
        "provide_bilingual_name": "Fournir un nom et des descriptions <strong>bilingues.",
        "create_a_community": "Créer une collectivité",
        "community_details": "Détails de la collectivité",
        "community_classification": "Classification de la collectivité",
        "community_classification_Modal": "<span style=fontWeight:normal>la</span> classification de la collectivité",
        "terms": "Conditions d’utilisation des collectivités protégées",
        "invite_owners_members": "Inviter les responsables et les membres",
        "review_submit": "Vérifier et soumettre",
        "unclassified_button": "Je ne veux plus stocker de documents protégés.",
      "CommPurpose": 'L’équipe de soutien GCÉ doit connaître l’objectif de la nouvelle collectivité pour déterminer si elle peut être <strong>approuvée</strong>.<br/> Cette information n’apparaîtra pas sur votre site. Rédiger l’information dans la langue officielle de votre choix. Max. 500 caractères.',
      "title_complete": "Terminé!",
      "thank_you": "Merci de nous avoir fourni ces renseignements.",
      "complete_content":"Vous recevrez un courriel lorsque votre collectivité aura été créée et tous les renseignements nécessaires pour commencer! (Dans les 48 heures du lundi au vendredi). <p>Si vous ne recevez pas de courriel ou si vous avez des questions, veuillez soumettre une demande de service à l’aide du <u>portail de soutien GCÉchange</u>.</p>",
      "complete_img_alt":"Trois personnes qui font la fête",
      "complete_button": "Page d’accueil de GCÉchange",
        "commPurpose_title": "Objet de la collectivité",
        "commPurpose_Modal": "<span style=fontWeight:normal>l'</span>objet de la collectivité",
        "commPurpose_desc": 'L’équipe de soutien GCÉ doit connaître l’objectif de la nouvelle collectivité pour déterminer si elle peut être <strong>approuvée</strong>.',
        "commPurpose_Instruction": "Cette information n’apparaîtra pas sur votre site. Rédiger l’information dans la langue officielle de votre choix. Max. 500 caractères.",
        "engName_title": 'Nom de la collectivité en anglais',
        "engName_Modal": '<span style=fontWeight:normal>le</span> nom de la collectivité en anglais',
        "engName_desc": "Le nom de la collectivité est le titre de votre collectivité. Créer un nom court et descriptif. Un nom bilingue respecte la Loi sur les langues officielles et permet aux autres de trouver plus facilement votre collectivité dans le catalogue GCÉchange. ",
        "engName_Instruction": "Utiliser des mots-clés, et non des abréviations, pour une meilleure visibilité. La longueur doit être de 5 à 125 caractères et les caractères spéciaux ne sont pas autorisés",
        "frCommName_title": "Nom de la collectivité en français",
        "frCommName_Modal": "<span style=fontWeight:normal>le</span> nom de la collectivité en français",
        "frCommName_desc": "Le nom de la collectivité est le titre de votre collectivité. Créer un nom court et descriptif. Un nom bilingue respecte la Loi sur les langues officielles et permet aux autres de trouver plus facilement votre collectivité dans le catalogue GCÉchange. ",
        "frCommName_Instruction": 'Utiliser des mots-clés, et non des abréviations, pour une meilleure visibilité. La longueur doit être de 5 à 125 caractères et les caractères spéciaux ne sont pas autorisés.',
        "shEngDesc_title": 'Brève description en anglais',
        "shEngDesc_Modal": "<span style=fontWeight:normal>une</span> brève description en anglais",
        "shEngDesc_desc": 'La description de la collectivité sera visible pour les utilisateurs lorsqu’ils utiliseront la page « Toutes les collectivités » et lorsqu’ils font une recherche.',
        "shEngDesc_Instruction": 'Max. 33 caractères.',
        "shFrDesc_title": 'Brève description en français',
        "shFrDesc_Modal": '<span style=fontWeight:normal>une</span> brève description en français',
        "shFrDesc_desc": 'La description de la collectivité sera visible pour les utilisateurs lorsqu’ils utiliseront la page « Toutes les collectivités » et lorsqu’ils font une recherche.',
        "shFrDesc_Instruction": 'Max. 33 caractères.',
        "owners_Instruction": 'Commencez à taper le nom de famille d’un membre pour le trouver et l’ajouter.',
        "members_Instruction": 'Commencez à taper le nom de famille d’un membre pour le trouver et l’ajouter.',
        "community_classification_desc": "Pour modifier la classification de votre collectivité, vous devez retourner à la page sur la classification de la collectivité et lire les conditions d’utilisation.",
        "community_classification_link": "Accéder à la page Classification de la collectivité",
        "collaborate": "Collaborer avec des collègues d’autres ministères en utilisant Microsoft Teams et Sharepoint pour échanger des idées, des documents, et bien plus encore…",
        "a_few_things": "Quelques directives avant de commencer",
        "to_create": "Pour créer une collectivité, vous devrez :",
        "bilingual_name_smallText": "Indiquer le nom et la description de la collectivité et le tout doit être entièrement bilingue pour respecter la <i>Loi sur les langues officielles</i>",
        "indentify_one_more_owner": "Indiquer au moins <strong className={ styles.blue }>un autre responsable</strong>",
        "indentify_one_more_owner_smallText": "La désignation de plus d’un responsable garantit la continuité de la collectivité en cas de départ d’un responsable",
        "protected_or_unclassified": "Indiquer si votre collectivité présentera des renseignements de niveau <strong className={ styles.blue }>Protégé</strong> ou <strong className={ styles.blue }>Non classifié</strong>",
        "protected_or_unclassified_smallText": "Les conditions de création d’une collectivité protégée devront être acceptées avant la création d’une collectivité",
        "Lets_go": "C’est parti…",
        "comm_desc_title": "Description de la collectivité",
        "comm_name": "Nom de la collectivité",
        "unclassified_cardText": "Non, je n’ai pas besoin de stocker des renseignements protégés. <strong>Tous les utilisateurs pourront trouver votre collectivité et en faire la recherche</strong>.",
        "protected_cardText": "Oui, je dois stocker des renseignements protégés tels que des formulaires de consentement, des renseignements personnels, des coordonnées de personnes ou d’organisations, des documents financiers ou d’autres documents qui, s’ils sont compromis, <strong>pourraient causer un préjudice à une personne, à une organisation ou au gouvernement</strong>.",
        "comm_classification_para1": "Vous devrez peut-être conserver des documents ou des renseignements protégés dans la bibliothèque de votre collectivité. GCÉchange peut fournir un espace pour des renseignements protégés jusqu’au niveau Protégé B. Tout d’abord, il faut savoir si vous allez stocker des documents protégés dans votre collectivité.",
        "unclassified": "Les renseignements que vous stockez sont non classifiés, vous n’avez donc pas besoin d’un espace pour documents classifiés. Veillez à <strong>ne pas stocker</strong> de documents classifiés dans votre bibliothèque. Si vous ne savez pas quels renseignements sont classifiés, vous pouvez consulter la politique de sécurité de votre ministère ou la direction de la gestion de l’information.",
        "protected_para1": "Il semble que vous ayez besoin d’un espace pour stocker des documents et des renseignements protégés sur GCÉchange. Il existe quelques conditions d’utilisation pour les collectivités protégées.",
        "protected_para2": "La sécurité des documents est la responsabilité de tous les membres de GCÉchange, y compris la vôtre. Nous vous demandons de passer en revue les directives de sécurité de votre ministère afin de veiller à ce que vous connaissiez bien vos responsabilités et pour que vous puissiez informer vos membres de leurs responsabilités, avant d’accepter les conditions d’utilisation ci-dessous.",
        "agree_to_terms": "J’accepte les conditions d’utilisation ci-dessous",
        "chk1": "Les collectivités protégées ne sont visibles que par les membres qui ont été invités par le responsable de la collectivité.",
        "chk1b": "Je comprends que ma collectivité ne sera visible que par les membres.",
        "chk2": "Tous les membres d’une collectivité protégée doivent disposer d’un téléphone délivré par le gouvernement dont l’application Microsoft Authenticator est activée.",
        "chk2b": "Je comprends que les membres de ma collectivité doivent respecter ces exigences pour accéder à ma collectivité.",
        "chk3": "Tous les membres doivent utiliser un appareil délivré par le gouvernement et avoir activé MaClé pour accéder à une collectivité Protégé B.",
        "chk3b": "Je comprends que les membres de ma collectivité doivent respecter ces exigences pour accéder à ma collectivité.",
        "chk4": "Les utilisateurs doivent posséder une cote de fiabilité pour accéder à un espace protégé, et avoir besoin de connaître les renseignements qui y sont stockés.",
        "chk4b": "Je comprends que les membres de ma collectivité doivent respecter ces exigences pour accéder à ma collectivité.",
        "chk5": "Nous ne pouvons pas garantir un soutien opportun pour les collectivités classifiées. Notre équipe de soutien n’a pas d’accès direct à ces sites tant qu’ils ne sont pas inscrits en tant que membres.",
        "chk5b": "J’accepte un accès limité aux services de soutien de GCÉchange.",
        "chk6": "Seuls les utilisateurs ayant besoin de connaître des renseignements protégés doivent être inclus comme membres dans une collectivité. Lorsqu’un membre change de rôle, ce besoin de savoir change également.",
        "chk6b": "Je passerai régulièrement en revue la liste des membres de ma collectivité et le nom des membres qui ont changé de rôle sera retiré.",
        "chk7": "La politique de conservation de GCÉchange est limitée à 2 ans pour tous les documents et on devrait seulement s’en servir pour stocker des renseignements transitoires.",
        "chk7b": "J’accepte de sauvegarder les documents de ma collectivité dans le dépôt officiel de mon ministère s’ils contiennent des renseignements à valeur opérationnelle.",
        "invite_owners_para1": "En tant que responsable de GCÉchange, vous pouvez modifier votre collectivité et y inviter d’autres utilisateurs afin qu’ils puissent collaborer avec vous dans Microsoft Teams.",
        "invite_owners_para2": "Pour l’instant, vous devez <strong>ajouter au moins un responsable supplémentaire</strong> avant de créer votre collectivité. Vous pouvez <strong>ajouter des membres</strong> à votre collectivité GCÉchange avant qu’elle ne soit mise en ligne. Vous ne pouvez ajouter que des personnes qui <strong>ont déjà un compte GCÉchange</strong>. Vous pouvez inviter des collègues à GCÉchange ci-dessous.",
        "invite_owners_para3": "Si vous ne souhaitez pas encore inviter de membres, c’est correct. Nous vous fournirons des instructions détaillées sur la manière de procéder une fois que votre collectivité aura été créée.",
        "invite_owners": "Inviter les responsables",
        "invite_members": "Inviter les membres",
        "invite_user_not_found": "<strong>Vous ne trouvez pas quelqu’un?</strong> Il est probable qu’il ne se soit pas encore inscrit à GCÉchange. Vous pouvez l’inviter à rejoindre GCÉchange en utilisant le bouton ci-dessous. Une fois l’enregistrement effectué, vous pourrez l’ajouter à votre collectivité.",
        "invite_a_colleague": "Inviter un collègue à GCÉchange",
        "review_info": "Vérifiez que les renseignements ci-dessous sont exacts ou modifiez-les.",
        "prev_btn": "Précédent",
        "next_btn": "Suivant",
        "submit_btn": "Allons-y",
        'eng_desc': 'Description en anglais',
        'fr_desc': 'Description en français',
        'owners': 'Propriétaires',
        'members': 'Membres',
        'close': 'Fermer',
        'you_must': 'Vous devez',
        'provide': '<span style="fontWeight:normal"> fournir </span>',
        'agree':'<span style="fontWeight:normal"> accepter toutes les </span>',
        'forget': 'Vous avez oublié quelque chose?',
        'before_proceeding': 'avant de poursuivre',
        'and': '<span style="fontWeight:normal"> et </span>',
        'the': 'le',
        'classification': 'Classification',
        'term_of_use': 'Conditions d’utilisation',
        'owners_and_members': 'Propriétaires et membres',
        'unclassified_cardTitle': 'Collectivité non classifiée',
        'protected_cardTitle': 'Collectivité Protégé A ou B',
        'one_more_owner':'<span style="fontWeight:normal"> ajouter au moins un autre</span>  propriétaire',
        'second_owner': '<span style="fontWeight:normal"> un autre</span>  propriétaire',
        'select': '<span style="fontWeight:normal"> sélectionner </span>',
        'max500_validation': ' Max. 500 caractères.',
        'special_char_validation': 'Les caractères spéciaux ne sont pas autorisés.',
        'between_5_125_char_validation': 'La longueur doit être de 5 à 125 caractères.',
        'max33_validation':'Max. 33 caractères.',
        'field_required': 'Le champ est obligatoire.',

    } 
});