/* eslint-disable no-undef */
define([], function() {
  return {
      "secondcontent": "Deuxième contenu",
      "PropertyPaneDescription": "Description",
      "BasicGroupName": "Nom de groupe",
      "title_details": "Détails",
      "provide_bilingual_name": "Fournir un nom et des descriptions <strong>bilingues.",
      "create_a_commuinity": "Créer une collectivité",
      "community_details": "Détails de la collectivité",
      "community_classification": "Classification de la collectivité",
      "terms": "Conditions d’utilisation des collectivités protégées",
      "invite_owners_members": "Inviter les responsables et les membres",
      "review_submit":"Vérifier et soumettre",
      "unclassified_button": "Je ne veux plus stocker de documents protégés.",
      "CommPurpose": 'L’équipe de soutien GCÉ doit connaître l’objectif de la nouvelle collectivité pour déterminer si elle peut être <strong>approuvée</strong>.<br/> Cette information n’apparaîtra pas sur votre site. Rédiger l’information dans la langue officielle de votre choix. Max. 500 caractères.',
      "title_complete": "Terminé!",
      "thank_you": "Merci de nous avoir fourni ces renseignements.",
      "complete_content":"Vous recevrez un courriel lorsque votre collectivité aura été créée et tous les renseignements nécessaires pour commencer! (Dans les 48 heures du lundi au vendredi). <p>Si vous ne recevez pas de courriel ou si vous avez des questions, veuillez soumettre une demande de service à l’aide du <u>portail de soutien GCÉchange</u>.</p>",
      "complete_img_alt":"Trois personnes qui font la fête",
      "complete_button": "Page d’accueil de GCÉchange",
      "commPurpose_title": "Objet de la collectivité",
      "commPurpose_desc": 'L’équipe de soutien GCÉ doit connaître l’objectif de la nouvelle collectivité pour déterminer si elle peut être <strong>approuvée</strong>.',
      "commPurpose_Instruction": "Cette information n’apparaîtra pas sur votre site. Rédiger l’information dans la langue officielle de votre choix. Max. 500 caractères.",
      "engName_title": 'Nom de la collectivité en anglais',
      "engName_desc": "Le nom de la collectivité est le titre de votre collectivité. Créer un nom court et descriptif. Un nom bilingue respecte la Loi sur les langues officielles et permet aux autres de trouver plus facilement votre collectivité dans le catalogue GCÉchange. ",
      "engName_Instruction": "Utiliser des mots-clés, et non des abréviations, pour une meilleure visibilité. La longueur doit être de 5 à 125 caractères et les caractères spéciaux ne sont pas autorisés",
      "frCommName_title": "Nom de la collectivité en français",
      "frCommName_desc":"Le nom de la collectivité est le titre de votre collectivité. Créer un nom court et descriptif. Un nom bilingue respecte la Loi sur les langues officielles et permet aux autres de trouver plus facilement votre collectivité dans le catalogue GCÉchange. ",
      "frCommName_Instruction": 'Utiliser des mots-clés, et non des abréviations, pour une meilleure visibilité. La longueur doit être de 5 à 125 caractères et les caractères spéciaux ne sont pas autorisés.',
      "shEngDesc_title": 'Brève description en anglais',
      "shEngDesc_desc": 'La description de la collectivité sera visible pour les utilisateurs lorsqu’ils utiliseront la page « Toutes les collectivités » et lorsqu’ils font une recherche.',
      "shEngDesc_Instruction": 'Max. 33 caractères.',
      "shFrDesc_title": 'Brève description en français ',
      "shFrDesc_desc": 'La description de la collectivité sera visible pour les utilisateurs lorsqu’ils utiliseront la page « Toutes les collectivités » et lorsqu’ils font une recherche.',
      "shFrDesc_Instruction": 'Max. 33 caractères.',
      "owners_Instruction": 'Commencez à taper le nom de famille d’un membre pour le trouver et l’ajouter.',
      "members_Instruction": 'Commencez à taper le nom de famille d’un membre pour le trouver et l’ajouter.',
      "community_classification_desc": "Pour modifier la classification de votre collectivité, vous devez retourner à la page sur la classification de la collectivité et lire les conditions d’utilisation.",
      "community_classification_link": "Accéder à la page Classification de la collectivité "

  }
});