declare interface IScwWebPartStrings {
  PropertyPaneDescription: string;
  BasicGroupName: string;
  DescriptionFieldLabel: string;
  AppLocalEnvironmentSharePoint: string;
  AppLocalEnvironmentTeams: string;
  AppLocalEnvironmentOffice: string;
  AppLocalEnvironmentOutlook: string;
  AppSharePointEnvironment: string;
  AppTeamsTabEnvironment: string;
  AppOfficeEnvironment: string;
  AppOutlookEnvironment: string;
  title_details: string;
  provide_bilingual_name: string;
  create_a_community: string;
  community_details: string;
  // community_classification: string;
  // community_classification_Modal: string;
  // terms: string;
  invite_owners_title: string;
  review_submit: string;
  // unclassified_button: string;
  CommPurpose: string;
  title_complete: string;
  thank_you: string;
  complete_content: string;
  complete_content2: string;
  complete_img_alt: string;
  complete_button: string;

  
  commPurpose_title: string;
  commPurpose_Modal: string;
  commPurpose_desc: string;
  commPurpose_Instruction: string;
  engName_title: string;
  engName_Modal: string;
  engName_desc: string;
  engName_Instruction: string;
  frCommName_title: string;
  frCommName_Modal: string;
  frCommName_desc: string;
  frCommName_Instruction: string;
  shEngDesc_title: string;
  shEngDesc_desc: string;
  shEngDesc_Instruction: string;
  shFrDesc_title: string;
  shFrDesc_desc: string;
  shFrDesc_Instruction: string;
  owners_Instruction: string;
  owners_instruction_Callout: string;
  // members_Instruction: string;
  // community_classification_desc: string;
  // community_classification_link: string;
  collaborate: string;
  a_few_things: string;
  to_create: string;
  bilingual_name_smallText: string;
  indentify_one_more_owner: string;
  indentify_one_more_owner_smallText: string; 
  // protected_or_unclassified: string;
  // protected_or_unclassified_smallText: string;
  Lets_go: string;
  comm_desc_title: string;
  comm_name: string;
  // unclassified_cardText: string;
  // protected_cardText: string;
  comm_classification_para1: string;
  // unclassified: string;
  // protected_para1: string;
  // protected_para2: string;
  // agree_to_terms: string;
  // chk1: string;
  // chk1b: string;
  // chk2: string;
  // chk2b: string;
  // chk3: string;
  // chk3b: string;
  // chk4: string;
  // chk4b: string;
  // chk5: string;
  // chk5b: string;
  // chk6: string;
  // chk6b: string;
  // chk7: string;
  // chk7b: string;
  invite_owners_para1: string;
  invite_owners_para2: string;
  invite_owners_para3: string;
  invite_owners_label: string;
  invite_members: string;
  // invite_user_not_found: string;
  // invite_a_colleague: string;
  review_info: string;
  prev_btn: string;
  next_btn: string;
  submit_btn: string;
  eng_desc: string;
  fr_desc: string;
  owners: string;
  // members: string;
  close: string;
  you_must: string;
  provide: string;
  forget: string;
  before_proceeding: string,
  and: string;
  the: string;
  // classification: string;
  // term_of_use: string;
  owners_and_members: string;
  unclassified_cardTitle: string;
  protected_cardTitle: string;
  one_more_owner: string;
  // second_owner: string;
  // agree: string;
  shEngDesc_Modal: string;
  shFrDesc_Modal: string;
  select: string;
  failed_oops: string;
  failed_txt1: string;
  failed_txt2: string;
  failed_txt3: string;
  failed_txt4: string;
  submissionFailed: string;
  submitting_your_information: string;  max500_validation: string;
  special_char_validation: string;
  between_5_80_char_validation: string;
  max100_validation: string;
  infoIcon_CommPurpose : string;
  infoIcon_engName : string;
  infoIcon_frName : string;
  infoIcon_engDesc : string;
  infoIcon_frDesc : string;
  infoIcon_Owners : string;
  required: string;
  SP_TeamsLogos: string;
  valid_email :string;
  invalidEmail:string;
  is_not_valid: string;
  requestorUser: string;




}

declare module  'ScwWebPartStrings'  {
  const strings: IScwWebPartStrings;
  export = strings;
}
